export const ERROR_TIMEOUT = 'Timed out!'
export const ERROR_JSON_RESPONSE_EXTRACTION = 'Failed to extract the json from the response:'
export const ERROR_WEBSOCKET_CONNECTION_FAILURE = 'Failed to connect to Websocket!'
export const ERROR_WEBSOCKET_REQUEST_TIMEOUT = 'Websocket request expired!'
export const ERROR_DB_CLIENT = 'Failed connecting to the db client, is it running?'
export const ERROR_INVALID_PARAMETERS = 'Failed to validate object parameters'
